# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3533bbf818604ae1bb181a9c5b9b9305237b89917da7ef34dc9aab39c6ed1f7fb19ea510c99023f00c23fa6c59f4a30b8e7b6b9afee72f027ae88b9087352f

test:
  secret_key_base: a697dc2436d92a1bdc178a78176ff8a6d23974439c5d4b1b9c4040b18b0cfb9d9de193d12a851fbf5cf9473a7c8aa2bc9807db74004c78cc42e76f74f28300a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
